### ISSUE TITLE
Bug: 500 error after Install

### ISSUE THREAD

**Issue by nichtdu** [kershner/screenBloom#18]
After installation and connection to bridge app comes up with 500 error:

global name 'img_proc' is not defined.

Attempting to register app with Hue bridge...
Success!  Creating config file...
[2017-01-07 17:42:57,380] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "c:\programming\projects\hue_project\venv\lib\site-packages\flask\app.py", line 1988, in wsgi_app
  File "c:\programming\projects\hue_project\venv\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
  File "c:\programming\projects\hue_project\venv\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
  File "c:\programming\projects\hue_project\venv\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
  File "c:\programming\projects\hue_project\venv\lib\site-packages\flask\app.py", line 1625, in dispatch_request
  File "ScreenBloom.py", line 38, in index
  File "c:\programming\projects\hue_project\app\modules\utility.py", line 133, in display_check
NameError: global name 'img_proc' is not defined

**Comment by kershner** [comment]
Thanks for the bug report!

I think this is a missing DLL error that isn't being re-directed to the right page correctly for whatever reason.  Normally there is handling for this error.  Your info will be helpful in fixing whatever is causing it to break here.

In any case, since the registration succeeded you should be good to go as soon as you install the missing DLLs.

Here's one C++ redistributable guaranteed to have them:
[https://www.microsoft.com/en-us/download/details.aspx?id=29](https://www.microsoft.com/en-us/download/details.aspx?id=29)

Let me know if that works for you.

**Comment by nichtdu** [comment]
Worked now – but reboot was required

 

Von: Tyler Kershner [mailto:notifications@github.com] 
Gesendet: Samstag, 7. Januar 2017 18:45
An: kershner/screenBloom <screenBloom@noreply.github.com>
Cc: Niklas <nichtdu@gmx.net>; Author <author@noreply.github.com>
Betreff: Re: [kershner/screenBloom] Bug: 500 error after Install (#18)

 

Thanks for the bug report!

I think this is a missing DLL error that isn't being re-directed to the right page correctly for whatever reason. Normally there is handling for this error. Your info will be helpful in fixing whatever is causing it to break here.

In any case, since the registration succeeded you should be good to go as soon as you install the missing DLLs.

Here's one C++ redistributable guaranteed to have them:
https://www.microsoft.com/en-us/download/details.aspx?id=29

Let me know if that works for you.

**Comment by kershner** [comment]
Glad to hear it.  Just let me know if you run into any more issues!
