### ISSUE TITLE
ScreenBloom New Connection Issue

### ISSUE THREAD

**Issue by luciahillrains** [kershner/screenBloom#82]
Hello,

Apologies if I missed something that was obvious - I only saw an issue from 2017 with this issue but it was closed with no explanation.

This happens when I try to start screen bloom.  I'm using Windows 10.  I tried running it as Admin, I looked at the firewall settings and didn't see any issues.  

---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "ScreenBloom.py", line 455, in <module>
  File "C:\Programming\Python\screenbloom\app\modules\startup.py", line 40, in run
  File "C:\Programming\Python\screenbloom\app\modules\startup.py", line 63, in startup_checks
  File "C:\Programming\Python\screenbloom\app\modules\presets.py", line 122, in update_presets_if_necessary
  File "C:\Programming\Python\screenbloom\app\modules\hue_interface.py", line 46, in get_lights_list
  File "C:\Programming\Python\screenbloom\app\modules\hue_interface.py", line 118, in get_all_lights
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\requests\api.py", line 70, in get
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\requests\api.py", line 56, in request
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\requests\sessions.py", line 488, in request
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\requests\sessions.py", line 609, in send
  File "C:\Programming\Python\screenbloom\app\venv\lib\site-packages\requests\adapters.py", line 487, in send
ConnectionError: HTTPConnectionPool(host='192.168.0.15', port=80): Max retries exceeded with url: /api/I3a0D0bNzsZjZvZp6QWPS4wqo5bvG06ugxJrTBLx/lights (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x065CBED0>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

**Comment by kershner** [comment]
Hey there!  Yeah this is a pretty general connection error.

Have you been using ScreenBloom previously and this is new behavior?  Or is this error happening on your first attempt to launch the program?

It looks like maybe something in the **presets.py** file is complaining.  I wonder if maybe you've recently added bulbs or your setup has changed in some way making the presets file no longer valid in some way?

If you think that's possible, just nuke your presets file and you should be good to go.

**The file is located at:**
c:/Users/**Username**/AppData*/Roaming/screenBloom/**screenBloom_presets.json**

*You'll need to enable 'Show Hidden Files' to see this directory.

Let me know if the issue is still not resolved.

**Comment by thansen** [comment]
I am having the same issue(also started about 8 days ago). This however coincided with moving around a lot of network stuff and re-pairing hue lights. I nuked the presets.json file like you mentioned but the problem persists.
